spring:
  #数据源信息
  datasource:
    #数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #配置连接信息
    url: jdbc:mysql://localhost:3306/Spring?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #用户名
    username: root
    #密码
    password: 123456

#slf4j
logging:
  config: D:/IDEAWorkSpace/simple-project/measure-data/src/main/resources/logback.xml